### ISSUE TITLE
Separate fast tests and slow tests from each other

### ISSUE THREAD

**Issue by JesperBrink** [Hogfeldt/bioconda_recipe_gen#18]
Right now when running the tests, you have to wait for the slow tests (starting one or more docker containers) even though you only want to test all the smaller and faster tests, like the ones that just test if a method returns correct. 

We want a way to separate the tests into multiple test suites, to make it easier to only call some specific type of the tests.

**Comment by Hogfeldt** [comment]
This issue is deprecated.
